import uuid
import json
from typing import List, Dict, Any
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.schemas.opportunity import OpportunityMatch, OpportunityMatchResponse
from app.services.graph_service import GraphQueryService
from app.services.ai.providers import AIProviderFactory
from app.config import settings

class OpportunityService:
    @staticmethod
    async def match_opportunities(
        db: AsyncSession, 
        workspace_id: uuid.UUID, 
        entity_id: uuid.UUID, 
        entity_type: str, 
        target_type: str
    ) -> OpportunityMatchResponse:
        
        graph_service = GraphQueryService(db)
        
        # 1. Fetch the source entity's graph (depth=2 to get skills, past projects, etc.)
        source_graph = await graph_service.traverse(start_id=entity_id, workspace_id=workspace_id, depth=2)
        
        # 2. Fetch candidate targets based on target_type
        # For simplicity, we'll fetch all nodes of target_type in the workspace
        model_class = graph_service.type_to_model.get(target_type)
        if not model_class:
            return OpportunityMatchResponse(matches=[])
            
        stmt = select(model_class).where(model_class.workspace_id == workspace_id)
        # Check if the model has an archived_at column to exclude archived ones
        if hasattr(model_class, 'archived_at'):
            stmt = stmt.where(model_class.archived_at.is_(None))
            
        result = await db.execute(stmt)
        candidate_nodes = result.scalars().all()
        
        if not candidate_nodes:
            return OpportunityMatchResponse(matches=[])
            
        candidates_data = [graph_service.serialize_node(node) for node in candidate_nodes]
        
        # 3. Use AI to score and generate reasons/evidence/limitations
        # This is where we strictly enforce the structure.
        ai_provider = AIProviderFactory.get_provider(settings.AI_PROVIDER)
        
        prompt = f"""
        You are an intelligent opportunity matching engine.
        I will provide you with a source entity and its graph context (skills, past projects, connections), 
        and a list of candidate opportunities of type {target_type}.
        
        Your job is to match the source entity to the candidates.
        
        CRITICAL RULES:
        1. YOU MUST NEVER guarantee a match. ALWAYS provide limitations.
        2. Evidence MUST explicitly reference data from the source graph (e.g. 'You have Python in your expertise_areas').
        3. Score should be 0-100. Only return matches with score > 40.
        
        Source Graph Context:
        {json.dumps(source_graph, default=str)}
        
        Candidates:
        {json.dumps(candidates_data, default=str)}
        
        Return the result EXACTLY as a JSON array of objects with the following keys:
        - target_id (string)
        - target_name (string, e.g. name or title of the candidate)
        - score (integer)
        - reasons (array of strings)
        - evidence (array of strings)
        - limitations (array of strings - MUST NOT BE EMPTY)
        
        Do not return any markdown formatting around the JSON array. Just the JSON array.
        """
        
        try:
            ai_response = await ai_provider.generate_response(prompt)
            # Clean up markdown if AI accidentally included it
            if ai_response.startswith("```json"):
                ai_response = ai_response[7:-3]
            elif ai_response.startswith("```"):
                ai_response = ai_response[3:-3]
                
            matches_data = json.loads(ai_response.strip())
            
            matches = []
            for match in matches_data:
                matches.append(
                    OpportunityMatch(
                        target_id=match["target_id"],
                        target_type=target_type,
                        target_name=match.get("target_name", "Unknown"),
                        score=match["score"],
                        reasons=match.get("reasons", []),
                        evidence=match.get("evidence", []),
                        limitations=match.get("limitations", ["AI limitation generated by default."])
                    )
                )
                
            # Sort matches by score descending
            matches.sort(key=lambda x: x.score, reverse=True)
            return OpportunityMatchResponse(matches=matches)
            
        except Exception as e:
            print(f"Error matching opportunities: {e}")
            return OpportunityMatchResponse(matches=[])
