import React, { useState } from 'react';
import { BrainCircuit, Activity, BarChart3, Info } from 'lucide-react';
import { useWorkspaceStore } from '@/store/workspaceStore';
import { forecastingApi } from '@/api/forecastingApi';
import type { ForecastResponse } from '@/api/forecastingApi';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export default function Forecasting() {
  const { currentWorkspace } = useWorkspaceStore();
  const [projectId, setProjectId] = useState('');
  const [forecast, setForecast] = useState<ForecastResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerateForecast = async () => {
    if (!currentWorkspace || !projectId) return;

    setLoading(true);
    setError(null);
    setForecast(null);
    
    try {
      const result = await forecastingApi.generateProjectForecast(currentWorkspace.id, projectId);
      setForecast(result);
    } catch (err: any) {
      setError(err.response?.data?.detail || err.message || 'Failed to generate forecast');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
            <BrainCircuit className="h-6 w-6 text-indigo-500" />
            AI Forecasting
          </h1>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            Generate AI-powered outcome predictions based on historical and current data.
          </p>
        </div>
      </div>

      <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg p-4 flex items-start gap-3">
        <Info className="h-5 w-5 text-amber-500 mt-0.5" />
        <div className="text-sm text-amber-800 dark:text-amber-200">
          <p className="font-medium">Important Notice Regarding Forecasts</p>
          <p className="mt-1">
            All outputs generated here are strictly explicitly labeled as <strong>predictions</strong>. 
            No forecast generated by this system will auto-trigger any high-impact actions. Human review is required for any operational decisions.
          </p>
        </div>
      </div>

      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-6">
        <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Project Success Forecast</h2>
        <div className="flex gap-4">
          <div className="flex-1">
            <Input 
              placeholder="Enter Project ID" 
              value={projectId}
              onChange={(e) => setProjectId(e.target.value)}
              className="w-full"
            />
          </div>
          <Button 
            onClick={handleGenerateForecast}
            disabled={!projectId || loading}
          >
            {loading ? 'Analyzing...' : 'Generate Prediction'}
          </Button>
        </div>

        {error && (
          <div className="mt-4 p-3 bg-red-50 text-red-600 rounded-lg text-sm">
            {error}
          </div>
        )}

        {forecast && (
          <div className="mt-6 border-t border-gray-200 dark:border-gray-700 pt-6">
            <div className="flex items-center gap-2 mb-4">
              <Activity className="h-5 w-5 text-indigo-500" />
              <h3 className="text-lg font-medium text-gray-900 dark:text-white">
                Prediction Results
              </h3>
              <span className="ml-auto inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300">
                AI Prediction
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
              <div className="bg-gray-50 dark:bg-gray-900/50 p-4 rounded-lg border border-gray-200 dark:border-gray-700">
                <div className="text-sm text-gray-500 dark:text-gray-400">Confidence Score</div>
                <div className="text-2xl font-bold text-gray-900 dark:text-white mt-1">
                  {(forecast.confidence * 100).toFixed(1)}%
                </div>
              </div>
              <div className="bg-gray-50 dark:bg-gray-900/50 p-4 rounded-lg border border-gray-200 dark:border-gray-700">
                <div className="text-sm text-gray-500 dark:text-gray-400">Predicted Outcome</div>
                <div className="text-xl font-medium text-gray-900 dark:text-white mt-1 capitalize">
                  {forecast.prediction.outcome || 'Unknown'}
                </div>
              </div>
            </div>

            <div>
              <h4 className="text-sm font-medium text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                <BarChart3 className="h-4 w-4 text-gray-400" />
                Contributing Factors
              </h4>
              <ul className="space-y-2">
                {forecast.factors.map((factor, index) => (
                  <li key={index} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-300">
                    <span className="w-1.5 h-1.5 rounded-full bg-indigo-500 mt-1.5 flex-shrink-0" />
                    {factor}
                  </li>
                ))}
              </ul>
              {forecast.factors.length === 0 && (
                <p className="text-sm text-gray-500 italic">No specific factors identified.</p>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
