"""Add federation models

Revision ID: 2d0e3813642c
Revises: 37674849a30e
Create Date: 2026-08-12 14:26:56.777688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0e3813642c'
down_revision: Union[str, None] = '37674849a30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_federations',
    sa.Column('source_workspace_id', sa.UUID(), nullable=False),
    sa.Column('target_workspace_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'REVOKED', name='federationstatus'), nullable=False),
    sa.Column('shared_entities', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_federations', schema=None) as batch_op:
        batch_op.create_index('ix_federation_link', ['source_workspace_id', 'target_workspace_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workspace_federations_source_workspace_id'), ['source_workspace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_federations_target_workspace_id'), ['target_workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_federations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_federations_target_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_federations_source_workspace_id'))
        batch_op.drop_index('ix_federation_link')

    op.drop_table('workspace_federations')
    # ### end Alembic commands ###
