"""Add program_type and is_template to hackathons

Revision ID: bed382a0b57c
Revises: f9aac7a59a1b
Create Date: 2026-08-07 21:58:23.904165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed382a0b57c'
down_revision: Union[str, None] = 'f9aac7a59a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_type', sa.String(), nullable=False, server_default='hackathon'))
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_hackathons_is_template'), ['is_template'], unique=False)
        batch_op.create_index(batch_op.f('ix_hackathons_program_type'), ['program_type'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hackathons_program_type'))
        batch_op.drop_index(batch_op.f('ix_hackathons_is_template'))
        batch_op.drop_column('is_template')
        batch_op.drop_column('program_type')
