"""Add Hackathons

Revision ID: d9686c9452d9
Revises: 3aabbacf5652
Create Date: 2026-08-04 12:36:55.562674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9686c9452d9'
down_revision: Union[str, None] = '3aabbacf5652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organiser', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('official_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('max_team_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('workspace_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_hackathons_status'), ['status'], unique=False)
        batch_op.create_foreign_key('fk_hackathons_users_created_by', 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('website_url')
        batch_op.drop_column('is_online')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('workspace_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('workspace_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('hackathons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_online', sa.BOOLEAN(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_hackathons_users_created_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_hackathons_status'))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('workspace_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.drop_column('archived_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('max_team_size')
        batch_op.drop_column('registration_deadline')
        batch_op.drop_column('mode')
        batch_op.drop_column('official_url')
        batch_op.drop_column('organiser')

    # ### end Alembic commands ###
